[package]
name = "wildeos-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "wildeos-rust"
test = false
bench = false

[unstable]
build-std = ["core", "compiler_builtins"]
